Processors tests
FokusHuk/MakimaBot pull request #35
Opened 2024-09-23 09:02 UTC by Anton-Khan

2024-09-23 09:05 UTC, Anton-Khan commented
Ой, нужно было создать это пораньше 😳😳😳

2024-09-23 09:07 UTC, Anton-Khan commented
Что я натворил( Теперь ты никогда не заставишь себя это посмотреть 😔

2024-09-24 20:02 UTC, FokusHuk requested changes

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/BotController.cs
> +    // public async Task<IActionResult> GetStateAsync(CancellationToken cancellationToken)
Не пон, поч коммент

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/Processors/ChatMessageProcessorBase.cs
> +    public virtual bool СontinueAnyway { get => false; }
А чего оно паблик стало? Оно где то вне бейз класса используется?

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/Processors/ProcessorComponent.cs
> +    public DailyActivityProcessor DailyActivityProcessor { get; }
🤌🏼

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +public class TelegramTextMessageSender : ITelegramTextMessageSender
Давай полную обертку над telegramBotClient сделаем, прям все методы, и только ее будем использовать
Потому что если еще какой метод экстеншн заюзаем, который без интерфейса и в тесте не мокается, придется еще пилить обертку по такой логике
Кроме этого сейчас уже есть место, где два клиента для телеграма торчат (ActivityStatisticsEvent), общий и сендер

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +                                              bool? disableWebPagePreview = null,
Мы не хотим тут все параметры перечислять, они бесполезны
Давай только те, которые сейчас используются
Расширить потом интерфейс еще одним необязательным параметром не проблема

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +                "Неизвестная команда💔 @makima_daily_bot <команда> <параметры>", // todo: сообщить юзеру, что меншн это команда
Ну го тут раскроем, что когда меншеним тригерим команды. И что список доступных команд можно узнать введя @makima_daily_bot list, и похуй что ее нет пока. А если не похуй, то в ишью про эту команду докинь дод, что тут надо поправить коммент
И туду коммент удали

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +        var allowedCommands = _commands.Select(command => command.Name).ToArray(); // todo: что? зачем сейчас? почему? Кажется тут чего-то не хватает, например премиссий💔
Какой то рудимент после ночного хардкода гпт команды
Раз юзаджей нет, снеси просто

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> -        if (match.Count == 0)
Но эта проверка покрывала кейс, когда у тебя тегают бота просто. Типо текст "@makima_daily_bot". Новая проверка разве его покрывает?
Реглярка такое не сматчит же? Или сматчит?
`var commandName = match.First().Groups[1].Value;`
Если нет, то вот тут оно упадет потому что First. Надо на FirstOrDefault тогда поменять и тестом покрыть

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +                "Команда не распознана🙍‍♀️ запросите список доступных команд (list)",
Выше то же самое сообщение считай. Надо наверное вынести его константу.
А вообщем мы тут не можем как то проверки объединить по умному?
string.IsNullOrEmpty(commandName)
и
currentCommand is null

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +        if (string.IsNullOrEmpty(rawParameters))
А почему здесь вдруг появилась эта проверка? Не все команды с параметрами, такого не должно быть в кор хендлере
Эта проверка нужна только для гпт команды

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +    public async Task ProcessorReceiveMessage_ExistedUser_AddMessageToStatistics()
Нейминг тестов такой:
МетодКоторыйТестишь_ВходныеПараметрыИлиСпецУсловияТеста_ОжидамоеПоведение(ВозвращаемоеЗначение)
Тут будет по типу
ProcessChainAsync_ExistedUser_AddMessageToStatistics

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +    private static long _existedUserId = 123456;
Давай такие штуки делать константами, не статик и неймингом соотвествующим (_testChatId => TestChatId)

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +    private Mock<IDataContext> _dataContext;
Ни к чему мок переменную держать, делай сразу .Object в TestInitialize

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +        _cancellationToken = new CancellationToken();
Я тут не помню бест практис по токену, но для тестов кажется можно CancellationToken.None использовать

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/TelegramMessageExtension.cs
> +    public static Message AddText(this Message message, string text)
Отступ пропустил

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/TelegramMessageExtension.cs
> +    public static Message AddSticker(this Message message, string setName, string emoji)
WithSticker

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/TelegramMessageExtension.cs
> +    public static Message AddSticker(this Message message, string setName, string emoji)
От методов Add обычно не ожидаешь, что они вернут тебе объект обратно

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +        var newUser = _existedUserId + 1;
newUserId

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/RandomPhraseProcessorTests.cs
> +public class RandomPhraseProcessorWithoutRandom : RandomPhraseProcessor
file class

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +        _cancellationToken = new CancellationToken();
Я бы даже переменной не выносил его, а по местам просто использовал

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/RandomPhraseProcessorTests.cs
> +            .WithName("TestChat")
Наверное не стоит добавлять в билдер параметры, которые не нужны для тестов
Читать сложнее

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot/Model/Processors/GptMessageProcessor.cs
> -    private ChatCommandHandler _commandHandler;
Давай сразу переименуем этот хендлер и его тесты. А то я пока тесты читаю, у меня мозги плавятся
GptMessageProcessor => ChatCommandProcessor
Он же все команды ловит, вызывает хендлер команд, в котором уже вызывается обработчик нужной команды (гпт)

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/GptMessageProcessorTests.cs
> +    public async Task ReceiveMessageWith_WrongBotName_DoNothing()
Этот тест и второй можно объединить в один
текст месседжа выносишь в параметр теста, и добавляешь сверху DataRow, он несколько раз прогонится
\+ здесь еще можно проверить кейс, когда сообщение пустое и налл
Примерно так

```
[TestMethod]
[DataRow("@makiNO_daily_boD gpt random Promt")]
[DataRow("Makima @makima_daily_bot gpt random Promt")]
[DataRow("")]
[DataRow(null)]
public async Task ReceiveMessageWith_WrongBotName_DoNothing(string messageText)
```

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +public class TestAbstractChatMessageProcessor : ChatMessageProcessorBase
file scope

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +public class TestAbstractChatMessageProcessor : ChatMessageProcessorBase
Можно просто TestChatMessageProcessor

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +        });
ExecutionQueue.Add(ProcessorId);
return Task.CompletedTask;

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +    public List<int> ExecutionQueue { get; set; }
Меня смутил нейминг с queue, пока не разобрался, заем переменная эта нужна
Может получше назвать, чтобы сходу было понятно, что это порядок выполнения?
queue у меня со структурой данных ассоциируется, а слева я вижу тип списка
ProcessorsExecutionOrder мб

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +public class ChatMessageProcessorBaseTests
Надеюсь тут все корнер кейсы покрыты, я не хочу это в голове снова дебажить)

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/TestTelegramTextMessageSender.cs
> +        return Task.Run(() => MessageSent);
return Task.FromResult(MessageSent)

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/TestTelegramTextMessageSender.cs
> +    public Message MessageSent { get; set; }
SentMessage

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/TrustedChatProcessorTests.cs
> +        //Maybe will be some logic in ProcessAsync later
Давай без комментов

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/UntrustedChatProcessorTests.cs
> +        _dataContext.Verify(x => x.AddUnknownMessage(
Вместо этого наверное можно подсмотреть в стейт, и сделать проверку, что в unknownMessages лежит 1 сообщение

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/GptMessageProcessorTests.cs
> +        _chatCommandHandler = new Mock<IChatCommandHandler>();
Не увидел тестов на ChatCommandHandler, надо отдельно написать

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DefaultProcessorsChainFactoryTests.cs
> +public class DefaultProcessorsChainFactoryTests
Я бы не делал такой тест
У нас есть уже тесты, которые проверяют, что:
1. ChatMessageProcessorBase работает, то есть цепочки валидно выполняются
2. Отдельный тест на каждый процессор, который все его кейсы покрывает

Здесь просто какой то монструозный дубликат, который еще и поддерживать сложно, потому что компоненты могут добавляться, меняться, удаляться

2024-09-24 20:02 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/DefaultProcessorsChainFactoryTests.cs
> +public class DefaultProcessorsChainFactoryTests
Это вообще больше на интеграционный тест похоже, который совсем не так нужно делать

2024-09-25 00:10 UTC, Anton-Khan commented on MakimaBot/Model/Processors/ChatMessageProcessorBase.cs
> +    public virtual bool СontinueAnyway { get => false; }
оставил protected

2024-09-25 00:11 UTC, Anton-Khan commented on MakimaBot/Model/Processors/ProcessorComponent.cs
> +    public DailyActivityProcessor DailyActivityProcessor { get; }
некрасиво, мне было неприятно смотреть

2024-09-25 00:11 UTC, Anton-Khan commented on MakimaBot/Model/Processors/ProcessorComponent.cs
> +    public DailyActivityProcessor DailyActivityProcessor { get; }
🤌🏼

2024-09-25 00:25 UTC, Anton-Khan commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +public class TelegramTextMessageSender : ITelegramTextMessageSender
Они все не мокаются. этот пр вообще должен был содержать только это изменение. как proof of concept.
Во многих местах используется только sendTextMessage, поэтому делал только его. В нескольких местах юзается с  разными параметрами, поэтому я добавил вообще все(на будущее так сказать).

Думал разграничить обертки, чтобы там где это не нужно даже доступа не было к ненужным методам.
Сервис то в любом случае singleton. Ну будем мы прокидывать разные обертки в один класс, и что? Разве это повлияет как-то на производительность или время сборки - не думаю.

К примеру в TelegramBotClient юзаются GetMeAsync, GetHashCode, а SendTextMessage нет.  Вопрос: зачем ему вообще знать про sendTextMessage? И наоборот для процессоров.
ChatMessageHandler использует только GetUpdatesAsync.

2024-09-25 00:35 UTC, Anton-Khan commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +public class TelegramTextMessageSender : ITelegramTextMessageSender
ChatEventHandle использует только GetChatAsync. И то это под вопросом, если честно.
```
 if (chat.Username != null && chat.Username.Contains(chatState.Name, StringComparison.OrdinalIgnoreCase)
      || chat.Title != null && chat.Title.Contains(chatState.Name, StringComparison.OrdinalIgnoreCase))
```
Зачем эта проверка вообще? Я не особо понимаю.

Более того, зачем нам вообще обращаться тут к telegramApi? 

```
    private async Task HandleChatEventsAsync(ChatState chatState)
    {
        var chat = await _telegramBotClient.GetChatAsync(chatState.ChatId);
        _dataContext.GetChatStateById(chatState.ChatId).Name
        
        if (chat.Username != null && chat.Username.Contains(chatState.Name, StringComparison.OrdinalIgnoreCase)
            || chat.Title != null && chat.Title.Contains(chatState.Name, StringComparison.OrdinalIgnoreCase))
        {
            foreach (var chatEvent in _chatEvents)
            {
                if (chatEvent.ShouldLaunch(chatState))
                {
                    await chatEvent.HandleEventAsync(_telegramTextMessageSender, chatState);
                    await _dataContext.SaveChangesAsync();
                }
            }
        }
    }
```
Тут же буквально передаётся chatState из dataContext и за чем то сверяется с telegramApi. "А точно ли есть чат с таким именем ???"

2024-09-25 00:43 UTC, Anton-Khan commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +public class TelegramTextMessageSender : ITelegramTextMessageSender
Слушай, я наверно создам issue. Ибо, а что если пользователь сменил имя чата? Все, он перестал поддерживаться? мб лучше через id тогда?

2024-09-25 00:47 UTC, Anton-Khan commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +                                              bool? disableWebPagePreview = null,
Ну вот тут в основном согласен. С другой стороны, они все равно дефолтные. Просто для чистоты кодовой базы?
(в нескольких местах используются одни параметры в друих другие)

Но в целом да, где-то половина параметров метода сейчас вообще не юзаются

2024-09-25 00:48 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +        var allowedCommands = _commands.Select(command => command.Name).ToArray(); // todo: что? зачем сейчас? почему? Кажется тут чего-то не хватает, например премиссий💔
это сейчас рудимент, т.к. только gpt-команда и существует

2024-09-25 00:59 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> -        if (match.Count == 0)
НЕТ, в этом то и суть 

Эта регулякра работает следующим образом ^@makima_daily_bot\s*([a-z]*)\s*(.*)$

| name   | parameter           | matchCount |
|--------|---------------------|------------|
| input: | "@makima_daily_bot" |            |
| match  | @makima_daily_bot   | 1 раз      |
| group1 | empty string        |            |
| group2 | empty string        |            |

2024-09-25 01:04 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> -        if (match.Count == 0)
при этом сюда попадают только сообщения, которые начинаются с "@makima_daily_bot".
То есть здесь не сматчится наверно только подобное "@makima_daily_botdskfdskgjgsjglsgksgkglksgkd".
Но это нужно поправить уровнем выше.

2024-09-25 01:08 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> -        if (match.Count == 0)
АВХхавхав, а нет, сматчится. чет ору. Нужно править регулярку

| name   | parameter           | matchCount |
|--------|---------------------|------------|
| input: | "@makima_daily_botdskfdskg" |            |
| match  | @makima_daily_bot   | 1 раз      |
| group1 | dskfdskg       |  1 раз          |
| group2 | empty string        |            |

2024-09-25 03:00 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/DefaultProcessorsChainFactoryTests.cs
> +public class DefaultProcessorsChainFactoryTests
Уничтожил, низвёл до атомов ©Thanos

2024-09-25 03:11 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/TrustedChatProcessorTests.cs
> +        //Maybe will be some logic in ProcessAsync later
Уничтожил, низвёл до атомов ©Thanos

2024-09-25 03:13 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/TestTelegramTextMessageSender.cs
> +    public Message MessageSent { get; set; }
♻️ теперь так хд

2024-09-25 03:15 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/TestTelegramTextMessageSender.cs
> +        return Task.Run(() => MessageSent);
👌

2024-09-25 03:20 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +    public List<int> ExecutionQueue { get; set; }
👌

2024-09-25 03:20 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +        });
👌

2024-09-25 03:20 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +public class TestAbstractChatMessageProcessor : ChatMessageProcessorBase
👌

2024-09-25 03:24 UTC, Anton-Khan commented on MakimaBot/Model/Processors/GptMessageProcessor.cs
> -    private ChatCommandHandler _commandHandler;
👌

2024-09-25 03:25 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/RandomPhraseProcessorTests.cs
> +public class RandomPhraseProcessorWithoutRandom : RandomPhraseProcessor
👌

2024-09-25 03:26 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +        var newUser = _existedUserId + 1;
👌

2024-09-25 03:27 UTC, Anton-Khan commented on MakimaBot.Tests/TelegramMessageExtension.cs
> +    public static Message AddSticker(this Message message, string setName, string emoji)
👌

2024-09-25 03:28 UTC, Anton-Khan commented on MakimaBot.Tests/TelegramMessageExtension.cs
> +    public static Message AddText(this Message message, string text)
🤌

2024-09-25 03:34 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +        _cancellationToken = new CancellationToken();
👌

2024-09-25 03:34 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +    public async Task ProcessorReceiveMessage_ExistedUser_AddMessageToStatistics()
👌

2024-09-25 03:35 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +        if (string.IsNullOrEmpty(rawParameters))
Да, она там и правда лишняя (дублирует логику ниже по уровню). Видио не заметил, после того, как увидел "рудимент" в этом методе

2024-09-25 03:38 UTC, Anton-Khan commented on MakimaBot/Model/BotController.cs
> +    // public async Task<IActionResult> GetStateAsync(CancellationToken cancellationToken)
а потому, что туда передаётся _dataContext как IDataContext. А у этого интерфейса нет доступа к полю State

2024-09-25 03:59 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +    private static long _existedUserId = 123456;
👌

2024-09-25 04:53 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> -        if (match.Count == 0)
короче глять это issue https://github.com/FokusHuk/MakimaBot/issues/38

2024-09-25 05:01 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +                "Неизвестная команда💔 @makima_daily_bot <команда> <параметры>", // todo: сообщить юзеру, что меншн это команда
можно считать, что сделал

2024-09-25 05:02 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +                "Неизвестная команда💔 @makima_daily_bot <команда> <параметры>", // todo: сообщить юзеру, что меншн это команда
естественно похуй

2024-09-25 05:02 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +        var allowedCommands = _commands.Select(command => command.Name).ToArray(); // todo: что? зачем сейчас? почему? Кажется тут чего-то не хватает, например премиссий💔
убрал

2024-09-25 05:07 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +                "Команда не распознана🙍‍♀️ запросите список доступных команд (list)",
## Нажми на фотку)
[![IMAGE ALT TEXT HERE](https://3fc4ed44-3fbc-419a-97a1-a29742511391.selcdn.net/coub_storage/coub/simple/cw_timeline_pic/a6495bb6cba/b8b88cd5640e9c54fd72b/1587793881_image.jpg)](https://youtu.be/zjoXkH7LQrE?si=mNulNqh1t9NGQmIV&t=2)

2024-09-26 20:13 UTC, FokusHuk commented on MakimaBot/Model/BotController.cs
> +    // public async Task<IActionResult> GetStateAsync(CancellationToken cancellationToken)
Ну давай добавим, или методом закроем
Не хочу доступ к этому роуту терять

2024-09-26 20:20 UTC, FokusHuk commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +public class TelegramTextMessageSender : ITelegramTextMessageSender
Такое ишью но можно

> Думал разграничить обертки, чтобы там где это не нужно даже доступа не было к ненужным методам.

У тебя сейчас один телеграм клиент везде, со всеми возможными методами
Инкапуслировать куски в разных обертах, по частям, это супер не практично
Классы начинают принимать кучу параметров, которые юзают внутри один и тот же клиент
А если у тебя глубокая вложенность (а такое бывает), то ты эти обёртки все дальше прокидывать вынужден
Это ни к чему

2024-09-26 20:21 UTC, FokusHuk commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +                                              bool? disableWebPagePreview = null,
Для чистоты, да

2024-10-04 01:38 UTC, Anton-Khan commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +public class TelegramTextMessageSender : ITelegramTextMessageSender
Появилась обертка над TelegramBotClient

2024-10-04 01:46 UTC, Anton-Khan commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +public class TelegramTextMessageSender : ITelegramTextMessageSender
завел issue https://github.com/FokusHuk/MakimaBot/issues/40

2024-10-04 01:46 UTC, Anton-Khan commented on MakimaBot/Model/TelegramTextMessageSender.cs
> +                                              bool? disableWebPagePreview = null,
почистил ненужные параметры

2024-10-04 01:47 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +                "Неизвестная команда💔 @makima_daily_bot <команда> <параметры>", // todo: сообщить юзеру, что меншн это команда
это нужно будет переписать после https://github.com/FokusHuk/MakimaBot/issues/38

2024-10-04 01:48 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +                "Команда не распознана🙍‍♀️ запросите список доступных команд (list)",
после https://github.com/FokusHuk/MakimaBot/issues/38

2024-10-04 01:55 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/DailyActivityProcessorTests.cs
> +    private Mock<IDataContext> _dataContext;
Мне она нужна, чтобы делать _dataContext.Verify()
(чтобы она задавалась в [TestInitialize], и только  _dataContext.Verify() был в тестовых методах)

2024-10-04 01:57 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/RandomPhraseProcessorTests.cs
> +            .WithName("TestChat")
👌

2024-10-04 02:06 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/GptMessageProcessorTests.cs
> +    public async Task ReceiveMessageWith_WrongBotName_DoNothing()
👌

2024-10-04 02:06 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +public class ChatMessageProcessorBaseTests
честно признаться, я тоже

2024-10-04 02:12 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/UntrustedChatProcessorTests.cs
> +        _dataContext.Verify(x => x.AddUnknownMessage(
А смысл? Я тут проверяю, что вызывался метод, который кладет сообщение об ошибке в стейт.
А как он его кладет нам наверно в этом тесте без разницы, не? Это же уже ответственность dataContext по логике.

2024-10-04 02:15 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/GptMessageProcessorTests.cs
> +        _chatCommandHandler = new Mock<IChatCommandHandler>();
Давай все-таки обождем. Там сначала нужно регулярку править -> сам хендлер(в зависимости от новой регулярки) и т.д.

2024-10-04 02:16 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/GptMessageProcessorTests.cs
> +        _chatCommandHandler = new Mock<IChatCommandHandler>();
ну либо я в этом же pr решу issue с регуляркой и перепешу handler (если потребуется)

2024-10-04 02:26 UTC, Anton-Khan commented on MakimaBot/Model/BotController.cs
> +    // public async Task<IActionResult> GetStateAsync(CancellationToken cancellationToken)
Просто property добавил в IDataContext

2024-10-04 02:28 UTC, Anton-Khan commented
Короче, сначала нужно править регулярку, а потом наверно посать тесты на chatCommandHandler. Боюсь там может слегка поменяться поведение

2024-10-04 18:28 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/ChatMessageProcessorBaseTests.cs
> +public class ChatMessageProcessorBaseTests
lgtm

2024-10-04 18:30 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/UntrustedChatProcessorTests.cs
> +        _dataContext.Verify(x => x.AddUnknownMessage(
Валидно да

2024-10-04 18:32 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/GptMessageProcessorTests.cs
> +        _chatCommandHandler = new Mock<IChatCommandHandler>();
Я накинул дод в то ишью про регулярку, тут не трогаем

2024-10-04 18:42 UTC, FokusHuk requested changes

2024-10-04 18:42 UTC, FokusHuk commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +    public Task<Chat> GetChatAsync(ChatId chatId, CancellationToken cancellationToken = default)
Давай cancellationToken все таки обязательный
Или почему так сделал?

2024-10-04 18:42 UTC, FokusHuk commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +        return _telegramBotClient.GetChatAsync(chatId, cancellationToken);
Я бы лямбдой захуярил конечно)

2024-10-04 18:42 UTC, FokusHuk commented on MakimaBot/Model/Events/ActivityStatisticsEvent.cs
> +            var member = await _telegramBotClientWrapper.GetChatMemberAsync(chat.ChatId, stats.Key);
Чет тут мешанина какая то в классе
Через di прокидывается враппер и в метод, и оба еще и используется

2024-10-04 18:42 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/RandomPhraseProcessorTests.cs
> +                                              ITelegramBotClientWrapper telegramTextMessageSender)
Если переносишь параметры на некст строку, переноси и первый, это более удобочитаемый код стайл

2024-10-04 18:42 UTC, FokusHuk commented on MakimaBot/Model/Events/ActivityStatisticsEvent.cs
> +            var member = await _telegramBotClientWrapper.GetChatMemberAsync(chat.ChatId, stats.Key);
В остальных файлах тоже проверь, что такого нет

2024-10-04 18:45 UTC, Anton-Khan commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +    public Task<Chat> GetChatAsync(ChatId chatId, CancellationToken cancellationToken = default)
я посмотрел твой код. Там везде ты не прокидывал cancellationToken.
Но мб это ты проибався раньше

2024-10-04 18:46 UTC, Anton-Khan commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +        return _telegramBotClient.GetChatAsync(chatId, cancellationToken);
да я просто не люблю когда длинные строки, их переносить нужно. Не сказал бы что в таких случаях  удобнее читать лямбдой

2024-10-04 18:47 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/RandomPhraseProcessorTests.cs
> +                                              ITelegramBotClientWrapper telegramTextMessageSender)
кк

2024-10-04 18:56 UTC, FokusHuk commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +        return _telegramBotClient.GetChatAsync(chatId, cancellationToken);
Просто люблю такое, но на твой выбор

```
 public Task<Chat> GetChatAsync(ChatId chatId, CancellationToken cancellationToken = default) =>
       _telegramBotClient.GetChatAsync(chatId, cancellationToken);
```

2024-10-04 18:57 UTC, FokusHuk commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +    public Task<Chat> GetChatAsync(ChatId chatId, CancellationToken cancellationToken = default)
Мм, ничего не знаю, но оставь так если контракт меняется

2024-10-04 18:58 UTC, Anton-Khan commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +        return _telegramBotClient.GetChatAsync(chatId, cancellationToken);
без проблем. У меня просто есть такая шиза. Не выработан шаблон этих переносов. Я от файла к файлу по разному переношу(
Никак не могу прийти к одному шаблону

2024-10-04 19:20 UTC, Anton-Khan commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +    public Task<Chat> GetChatAsync(ChatId chatId, CancellationToken cancellationToken = default)
Да, я чекнул, туда не прокидывается токен

2024-10-04 19:23 UTC, Anton-Khan commented on MakimaBot/Model/TelegramBotClientWrapper.cs
> +        return _telegramBotClient.GetChatAsync(chatId, cancellationToken);
done

2024-10-04 19:26 UTC, Anton-Khan commented on MakimaBot/Model/Events/ActivityStatisticsEvent.cs
> +            var member = await _telegramBotClientWrapper.GetChatMemberAsync(chat.ChatId, stats.Key);
Опа, а вот тут красава

2024-10-04 19:26 UTC, Anton-Khan commented on MakimaBot/Model/Events/ActivityStatisticsEvent.cs
> +            var member = await _telegramBotClientWrapper.GetChatMemberAsync(chat.ChatId, stats.Key);
этого реально не должно быть

2024-10-04 19:47 UTC, Anton-Khan commented on MakimaBot/Model/Events/ActivityStatisticsEvent.cs
> +            var member = await _telegramBotClientWrapper.GetChatMemberAsync(chat.ChatId, stats.Key);
исправил

2024-10-04 19:48 UTC, Anton-Khan commented on MakimaBot/Model/Events/ActivityStatisticsEvent.cs
> +            var member = await _telegramBotClientWrapper.GetChatMemberAsync(chat.ChatId, stats.Key);
(прокидывается только через аргумент функции, т.к. так заложено в IChatEvent)

2024-10-04 19:50 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/RandomPhraseProcessorTests.cs
> +                                              ITelegramBotClientWrapper telegramTextMessageSender)
вроде исправил все, что нашел подобное

2024-10-04 20:18 UTC, FokusHuk approved these changes

2024-10-04 20:29 UTC, merged