Hotfix
FokusHuk/MakimaBot pull request #49
Opened 2024-10-05 22:31 UTC by Anton-Khan

* ChatCommandHandler
* ChatCommandHandlerTests
* refactoring (naming)

2024-10-05 22:42 UTC, Anton-Khan commented
https://github.com/FokusHuk/MakimaBot/issues/38
https://github.com/FokusHuk/MakimaBot/issues/36

2024-10-05 23:16 UTC, FokusHuk requested changes

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +    private string GetGptChatError(string commandError = "")
Давай вниз его опустим (метод в смысле)

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +    private string GetGptChatError(string commandError = "")
И это не gpt ошибка, мы же в общем хендлере

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
>                  parseMode: Telegram.Bot.Types.Enums.ParseMode.Markdown,
А зачем кстати так прописано?
Telegram.Bot.Types.Enums.ParseMode.Markdown
Там же неймспейс вше импортируется

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +        @makima\_daily\_bot это команда! {commandError}
А го без этого параметра commandError?
Шо то, шо это, одна ошибка же, давай сразу писать что не распознана

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot.Tests/ChatProcessorsTests/ChatCommandProcessorTests.cs
> +        await gptMessageProcessor.ProcessChainAsync(message, 0, CancellationToken.None);
Я мб снова чет не понимаю
Но почему тут gpt фигурирует
Это же комманд процессор, верхнеуровневая штука
В которой есть только комманд хендлер, который мы в тестах (конкретно этих) мокаем

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +        await _chatCommandHandler.HandleAsync(message, new TestChatStateBuilder().Build(), _telegramBotClientWrapper, CancellationToken.None);
Тут наверное строка пиздец длинная?)

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +        new List<ChatCommand> { new TestCommand(), new TestGptCommand() };
Давай тоже без упоминания gpt
Это же абстрактные команды, first, second

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +            _chatCommands.Select(x => (x as TestChatCommand).ExecutionCount).ToArray());
Assert.IsTrue(chatCommands.All(x => x.ExecutionCount == 0)

как то так упростить можно

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +        Assert.AreEqual(1, testCommand.ExecutionCount);
Наверн можно проверить еще, что у второй команды не было вызовов

2024-10-05 23:16 UTC, FokusHuk commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +    public override Task ExecuteAsync(Message message, ChatState chatState, string rawParameters, ITelegramBotClientWrapper _telegramBotClientWrapper, CancellationToken cancellationToken)
Не в одну строку пож

2024-10-05 23:46 UTC, Anton-Khan commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +            _chatCommands.Select(x => (x as TestChatCommand).ExecutionCount).ToArray());
ды

2024-10-05 23:46 UTC, Anton-Khan commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +        Assert.AreEqual(1, testCommand.ExecutionCount);
ды

2024-10-05 23:47 UTC, Anton-Khan commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +    public override Task ExecuteAsync(Message message, ChatState chatState, string rawParameters, ITelegramBotClientWrapper _telegramBotClientWrapper, CancellationToken cancellationToken)
ды

2024-10-05 23:47 UTC, Anton-Khan commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +        await _chatCommandHandler.HandleAsync(message, new TestChatStateBuilder().Build(), _telegramBotClientWrapper, CancellationToken.None);
ды

2024-10-05 23:50 UTC, Anton-Khan commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +        new List<ChatCommand> { new TestCommand(), new TestGptCommand() };
ды

2024-10-05 23:50 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +        @makima\_daily\_bot это команда! {commandError}
ды

2024-10-05 23:56 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
>                  parseMode: Telegram.Bot.Types.Enums.ParseMode.Markdown,
там Telegram.Bot.Types.Enums
добавил в using

2024-10-05 23:57 UTC, Anton-Khan commented on MakimaBot/Model/ChatCommands/ChatCommandHandler.cs
> +    private string GetGptChatError(string commandError = "")
Теперь это вообще константа

2024-10-06 00:01 UTC, Anton-Khan commented on MakimaBot.Tests/ChatProcessorsTests/ChatCommandProcessorTests.cs
> +        await gptMessageProcessor.ProcessChainAsync(message, 0, CancellationToken.None);
ды, это рудимент

2024-10-06 00:59 UTC, Anton-Khan commented
Сделал тут же таску про пересланные сообщения (просто добавил проверку)

https://github.com/FokusHuk/MakimaBot/issues/39

2024-10-06 10:46 UTC, FokusHuk approved these changes

2024-10-06 10:46 UTC, FokusHuk commented on MakimaBot/Model/Processors/ChatCommandProcessor.cs
> +               && message.ForwardDate is null;
Это тип единственный способ понять, что сообщение пересланное?? по дате?

2024-10-06 10:46 UTC, FokusHuk commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +            _chatCommands.Select(x => (x as TestChatCommand).ExecutionCount).ToArray());
А зачем тут везде приведение к TestChatCommand
Сделай _chatCommands сразу с правильным типом просто

2024-10-06 16:45 UTC, Anton-Khan commented on MakimaBot.Tests/ChatCommandTests/ChatCommandHandlerTests.cs
> +            _chatCommands.Select(x => (x as TestChatCommand).ExecutionCount).ToArray());
Я не могу загнать в file тип в поле класса

2024-10-06 16:45 UTC, Anton-Khan commented on MakimaBot/Model/Processors/ChatCommandProcessor.cs
> +               && message.ForwardDate is null;
нет, но пусть будет дата

2024-10-09 00:02 UTC, merged