Local State Added
FokusHuk/MakimaBot pull request #53
Opened 2024-10-13 03:47 UTC by Anton-Khan

Добавил новый LocalBucketClient : IBucketClient

Указываешь в config путь до state.json и там же "useLocalState" : "true"

Единственное, не забудь создать этот файл сначала и СКОПИРОВАТЬ туда стейт

2024-10-13 14:33 UTC, FokusHuk commented on MakimaBot/Model/Configuration/BucketOptions.cs
> +    [Required]
не реквайред, чтобы прод не ломать

2024-10-13 14:33 UTC, FokusHuk commented on MakimaBot/Model/Configuration/BucketOptions.cs
> +    [Required]
Можно даже без флага
iNullOrMeprty(PathToLocalState)
и дефолт поставить эмпти

2024-10-13 14:33 UTC, FokusHuk commented on MakimaBot/Model/State/LocalBucketClient.cs
> +public class LocalBucketClient : IBucketClient
Надо интерфейс получается переназвать, чтобы отражал только контракт
Потому что локально у тебя не бакет

2024-10-13 14:36 UTC, FokusHuk commented on MakimaBot/Model/State/LocalBucketClient.cs
> +                Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
джава скрипт?)

2024-10-13 14:36 UTC, FokusHuk commented on MakimaBot/Model/State/LocalBucketClient.cs
> +    public LocalBucketClient(string path)
давай инлайн конструктор

2024-10-13 22:54 UTC, Anton-Khan commented on MakimaBot/Model/Configuration/BucketOptions.cs
> +    [Required]
yeap

2024-10-13 22:54 UTC, Anton-Khan commented on MakimaBot/Model/State/LocalBucketClient.cs
> +public class LocalBucketClient : IBucketClient
IStateClient

2024-10-13 22:57 UTC, Anton-Khan commented on MakimaBot/Model/State/LocalBucketClient.cs
> +                Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
Да, это же локал. Зато в блокноте открытым држишь и смотришь уже в pretty-json формате.

(не уверен, но блокнот в 10 вроде лочил запись файла, а в 11 нет. Поэтому его просто можно открытым держать и наблюдать за стейтом без запросов в postman)

2024-10-13 22:57 UTC, Anton-Khan commented on MakimaBot/Model/State/LocalBucketClient.cs
> +    public LocalBucketClient(string path)
yeap

2024-10-13 23:29 UTC, Anton-Khan commented
Нужен хелп с version и changelog

Как мы накатываем патчи без смены версий

(просто -patch1 в version и в changelog все как раньше добавляется, только version без изменений?)

2024-10-14 01:21 UTC, Anton-Khan commented
Проверь Версию пж

2024-10-14 18:34 UTC, FokusHuk commented on MakimaBot/Model/State/LocalBucketClient.cs
> +public class LocalBucketClient : IBucketClient
Это StateProvider скорее?

2024-10-14 18:55 UTC, FokusHuk requested changes
Локально проверил же, что без новых параметров в конфиге все ок будет?

Давай наверное версию поднимем, 2.3.0 с дескрипшеном по человечески. Все таки это изменение

И го провайдер нейминг

IStateProvider
S3BucketStateProvider
LocalStorageStateProvider

2024-10-14 18:55 UTC, FokusHuk commented on MakimaBot/Startup.cs
> +        using (var serviceProvider = services.BuildServiceProvider())
Мб так, без билда?

```
services.AddSingleton<IStateClient>(provider =>
        {
            var bucketOptions = provider.GetRequiredService<IOptions<BucketOptions>>().Value;

            if (bucketOptions.UseLocalState)
                  GetLocalStateClient(services, bucketOptions);
            else
                  GetBucketClient(services, bucketOptions);
        });
```

2024-10-15 19:17 UTC, FokusHuk approved these changes

2024-10-15 19:17 UTC, FokusHuk commented on MakimaBot/Model/StateUpdater/StateUpdater.cs
> +        IStateProvider stateClient,
имя переменной забыл

2024-10-15 19:17 UTC, FokusHuk commented on MakimaBot/Startup.cs
> +        return new LocalStorageStateProvider(bucketOptions.PathToLocalState);
тут параметр сервисов лишний, да и ради одной строчки можно не выносить

2024-10-22 07:13 UTC, Anton-Khan commented on MakimaBot/Model/StateUpdater/StateUpdater.cs
> +        IStateProvider stateClient,
ага

2024-10-22 07:19 UTC, Anton-Khan commented on MakimaBot/Startup.cs
> +        return new LocalStorageStateProvider(bucketOptions.PathToLocalState);
параметр - да. 

а вот про не выносить - не согласен. Вот я смотрю на функу в которой CreateLocalStorageStateProvider и CreateS3BucketStateProvider. И сразу же понимаю для чего тут это. Они на одном уровне обстракции.

Ты же сам разносил все по функам в sturtup. Потому что накопилось и началась путаница. Добавить этот метод в 3 строчки - 5 сек. Зато выглядит чище сразу.

2024-10-22 07:25 UTC, merged

2024-10-22 17:54 UTC, FokusHuk commented on MakimaBot/Startup.cs
> +        return new LocalStorageStateProvider(bucketOptions.PathToLocalState);
🤌🏼